force-app/main/default/objects/Canvas_Course__c/Canvas_Course__c.object-meta.xml
<CustomObject>
    <description>Courses in Canvas.</description>
    <label>Canvas Course</label>
    <nameField>
        <label>Canvas Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canvas Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Canvas_Enrollment__c/Canvas_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Canvas Enrollment</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Canvas Enrollment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canvas Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Canvas_Enrollment__c/fields/Canvas_Course__c.field-meta.xml
<CustomField>
    <fullName>Canvas_Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Canvas Course enrolled.</description>
    <label>Canvas Course</label>
    <referenceTo>Canvas_Course__c</referenceTo>
    <relationshipLabel>Canvas Enrollments</relationshipLabel>
    <relationshipName>Canvas_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EnrollmentRequest.cls
public class EnrollmentRequest {
    
    //This is the lead enrolled.
    public Lead LeadEnrolled {get; set;}
    
    public Canvas_Course__c Course {get; set;}

	//This is the object stored in Salesforce    
    public Canvas_Enrollment__c Canvas_Enrollment {get; set;}

    //This is the object on the Canvas side from the API
    public CanvasUserEnrollment CanvasEnrollment {get; set;}
    
    //This is any message returned by the enroller
    public string Message {get; set;}
    
}